server {
  listen 443 ssl;
  ssl_certificate /certs/middle-auth-server.crt;
  ssl_certificate_key /certs/middle-auth-server.key;

  location / {
    proxy_pass http://middle-auth-server:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
